
try {
    //let x = noExite()
    throw  noExiste()
} catch (error) {
    alert(error)
}
